version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-data/prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: bridge
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - prometheus
    network_mode: bridge
